name: HRCommunity
version: ${version}
main: kr.hwaryuh.community.Main
api-version: '1.20'
author: useemeonascreen
depend:
  - MMOCore
  - MythicLib
commands:
  hcmu:
  profile:
    aliases: [프로필, vmfhvlf]
  friends:
    aliases: [친구, clsrn]
  party:
    aliases: [파티, vkxl]
  trade:
    aliases: [교환, 거래, ryghks, rjfo]
permissions:
  hcmu.reload:
    default: op