name: HRCommunity
version: ${version}
main: kr.hwaryuh.community.Main
api-version: '1.20'
author: useemeonascreen
depend:
  - MMOCore
  - MythicLib
commands:
  hcmu:
  프로필:
    aliases: vmfhvlf
  친구:
    aliases: clsrn
  파티:
    aliases: vkxl